# Configuração do Garage v2 (S3-compatible)
# Portas: admin=3900, rpc=3901, S3 API=3902, S3 web=3903

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "ee51a6c1c18d9e0cdd7cfdfb00434a46c930f0895c99139daaea177f4fc027a9"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3902"

[admin]
api_bind_addr = "[::]:3900"
