spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/absono}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    br.com.absono: INFO
    org.springframework.security: INFO
